name: Student Submission Review

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  validate_submission:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get changed files from PR
        run: |
          PR_NUM=${{ github.event.pull_request.number }}
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUM/files?per_page=100" \
            > pr_files.json
          jq -r '.[].filename' pr_files.json > changed_files.txt

      - name: Validate submission rules
        id: validate
        run: |
          set -euo pipefail

          ERROR_MSG=""

          while IFS= read -r file; do
            if [[ "$file" == "README.md" ]]; then
              ERROR_MSG+="❌ 不可修改 README.md\n"
            fi
            if [[ "$file" == "template.py" ]]; then
              ERROR_MSG+="❌ 不可修改 template.py\n"
            fi
          done < changed_files.txt

          NEW_FILES=$(grep "^submit/" changed_files.txt || true)
          MAIN_FILES=$(echo "$NEW_FILES" | grep -E '^submit/W4_[0-9]{9}\.py$' || true)
          MAIN_COUNT=$(echo "$MAIN_FILES" | grep -c ".*" || true)

          if [[ $MAIN_COUNT -ne 1 ]]; then
            ERROR_MSG+="❌ 你必須新增且僅有一個主程式檔 (submit/W4_<學號>.py)\n"
          fi

          if [[ -n "$ERROR_MSG" ]]; then
            echo "⚠️ 提交規則檢查未通過，請依照以下提示修改後再重新提交：" > pr_feedback.md
            echo "" >> pr_feedback.md
            echo -e "$ERROR_MSG" >> pr_feedback.md
            echo "invalid" > submission_status.txt
            exit 1
          else
            echo "✅ 提交符合規則，PR 流程正確！" > pr_feedback.md
            echo "valid" > submission_status.txt
          fi

      - name: Post feedback comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body-file: pr_feedback.md

  ai_review:
    needs: validate_submission
    runs-on: ubuntu-latest
    if: success()  # 只有通過規則才跑 AI
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install google-generativeai

      - name: Prepare diff for AI review
        run: |
          PR_NUM=${{ github.event.pull_request.number }}
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3.diff" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUM.diff" \
            > pr_diff.txt

      - name: Run Gemini AI Review
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python3 - <<EOF
          import os
          import google.generativeai as genai

          genai.configure(api_key=os.getenv("GEMINI_API_KEY"))

          diff = open("pr_diff.txt", encoding="utf-8").read()
          prompt = f"""你是一位資深軟體工程師。
          以下是學生的提交檔案修改，請進行簡短 Code Review。

          ### 優點
          - 至多 2 點

          ### 建議改進
          - 每檔案最多 3 條建議
          - 用 bullet point
          - 格式: - [行號] 問題簡述與改進建議

          ### 程式品質分數
          - 給 0~20 分
          - 僅輸出數字

          程式碼修改如下：
          {diff}
          """

          model = genai.GenerativeModel("gemini-1.5-flash")
          response = model.generate_content(prompt)
          review = getattr(response, "text", str(response))

          with open("review_result.md", "w", encoding="utf-8") as f:
              f.write(review)
          EOF

      - name: Post AI review
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body-file: review_result.md
  
  pytest_check:
    needs: validate_submission
    runs-on: ubuntu-latest
    if: success()  
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install pytest pandas numpy

      - name: Run pytest on student submission
        run: |
          mkdir -p test_results
          pytest test_W4.py --maxfail=1 --disable-warnings -q --tb=short | tee test_results/pytest_output.txt || true

      - name: Read pytest output
        id: read_pytest
        run: |
          cat test_results/pytest_output.txt >> pytest_content.txt
          echo "content<<EOF" >> $GITHUB_OUTPUT
          cat pytest_content.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post pytest results
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### 自動測試結果 (pytest)
            ```text
            ${{ steps.read_pytest.outputs.content }}
            ```



